; ============================================================
; GLOBAL ENVIRONMENT SETTINGS
; ============================================================
[env]
framework = arduino
monitor_speed = 115200

build_flags =
    -Wall
    -Wextra
    -std=gnu++17

lib_deps =
    adafruit/Adafruit GFX Library@^1.12.6 ;@ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0 ;@ ^1.10.3
    adafruit/Adafruit ILI9341@^1.6.3
    ;paulstoffregen/XPT2046_Touchscreen ; @ ^1.0.7 
    circuitstate/CSE_CST328@^0.0.5    


; ============================================================
; VARIANT A: GROUNDSTUDIO MARBLE PICO (RP2040)
; ============================================================
[env:marble_pico]
platform = raspberrypi
board = groundstudio_marble_pico
board_build.f_cpu = 133000000L
board_build.usb_mode = pico_sdk
build_flags = 
    ${env.build_flags} 
    -D SERVICEBOX_MARBLE

; ============================================================
; VARIANT B: WAVESHARE RP2350 TOUCH LCD 2.8
; ============================================================
[env:waveshare_rp2350]
; Uses maxgerhardt community platform to access native RP2350 architecture
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
; Fixed: Forces the compilation to use the official Pico 2 layout manifest with BS2 bootloader
board = rpipico2
board_build.core = earlephilhower
; Disables library archiving to prevent linker blocks inside GCC 12/14 pipelines
lib_archive = false
build_flags = 
    ${env.build_flags} 
    -D SERVICEBOX_WAVESHARE
upload_protocol = picotool
upload_flags = -f