// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------- //
// i2s_pio //
// ------- //

#define i2s_pio_wrap_target 0
#define i2s_pio_wrap 7
#define i2s_pio_pio_version 0

static __pio_const uint16_t i2s_pio_program_instructions[] = {
            //     .wrap_target
    0xe82e, //  0: set    x, 14           side 1
    0x6001, //  1: out    pins, 1         side 0
    0x0841, //  2: jmp    x--, 1          side 1
    0x7001, //  3: out    pins, 1         side 2
    0xf82e, //  4: set    x, 14           side 3
    0x7001, //  5: out    pins, 1         side 2
    0x1845, //  6: jmp    x--, 5          side 3
    0x6001, //  7: out    pins, 1         side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program i2s_pio_program = {
    .instructions = i2s_pio_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = i2s_pio_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_pio_wrap_target, offset + i2s_pio_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

